title: Mi blog Personal
description: Soy Gustavo, estudiante de ingeniería en sistemas computacionales, apasionado por la tecnología.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
